-- CreateTable
CREATE TABLE "CaseStudy" (
    "id" TEXT NOT NULL,
    "studentId" TEXT NOT NULL,
    "schoolClass" TEXT NOT NULL,
    "responsibleName" TEXT NOT NULL,
    "responsibleEmail" TEXT NOT NULL,
    "referredBy" TEXT NOT NULL,
    "hasDiagnosis" BOOLEAN NOT NULL,
    "diagnosis" TEXT,
    "informantName" TEXT NOT NULL,
    "informantRelation" TEXT NOT NULL,
    "informantEmail" TEXT NOT NULL,
    "responsiblePhone" TEXT NOT NULL,
    "informantPhone" TEXT NOT NULL,
    "pregnancyHistory" TEXT NOT NULL,
    "developmentMilestones" TEXT NOT NULL,
    "healthHistory" TEXT NOT NULL,
    "walkingDevelopment" TEXT NOT NULL,
    "speechDevelopment" TEXT NOT NULL,
    "sphincterControl" TEXT NOT NULL,
    "vision" TEXT NOT NULL,
    "hearing" TEXT NOT NULL,
    "sleep" TEXT NOT NULL,
    "usesMedication" BOOLEAN NOT NULL,
    "medicationName" TEXT,
    "medicationAtSchool" BOOLEAN NOT NULL,
    "feeding" TEXT NOT NULL,
    "foodSelectivity" BOOLEAN NOT NULL,
    "foodRestrictions" TEXT,
    "bathroomIndependence" TEXT NOT NULL,
    "dressing" TEXT NOT NULL,
    "locomotion" TEXT NOT NULL,
    "comprehensionLevel" TEXT NOT NULL,
    "socialInteraction" TEXT NOT NULL,
    "communicationTypes" TEXT[],
    "specificInterest" TEXT,
    "crisisRegulationStrategy" TEXT,
    "priorityAreas" TEXT[],
    "sensorySensitivity" TEXT[],
    "attention" TEXT NOT NULL,
    "frustrationTolerance" TEXT NOT NULL,
    "commandUnderstanding" TEXT NOT NULL,
    "classificationSkill" TEXT NOT NULL,
    "seriationSkill" TEXT NOT NULL,
    "spatialConcepts" TEXT NOT NULL,
    "readingLevel" TEXT NOT NULL,
    "mathReasoning" TEXT NOT NULL,
    "learningStyle" TEXT NOT NULL,
    "strengths" TEXT,
    "difficulties" TEXT,
    "currentSupports" TEXT,
    "aeeOpinion" TEXT NOT NULL,
    "suggestedAdaptations" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CaseStudy_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "CaseStudy" ADD CONSTRAINT "CaseStudy_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
