import "dotenv/config";

const {
  PORT,
  AZURE_OPENAI_DEPLOYMENT,
  AZURE_OPENAI_KEY,
  AZURE_OPENAI_ENDPOINT,
  AZURE_OPENAI_MODEL,
  GOOGLE_GENERATIVE_AI_API_KEY,
  GOOGLE_GENERATIVE_AI_MODEL,
  AI_SOURCE,
  PRIVATE_KEY_BASE64,
  PUBLIC_KEY_BASE64,
  SELF_BASE_URL,
  RESEND_API_KEY,
  EMAIL_FROM,
  EMAIL_CONFIRMATION_CODE_TTL_MINUTES,
  JWT_SECRET,
  FRONT_URL,
} = process.env;

export {
  AI_SOURCE,
  AZURE_OPENAI_DEPLOYMENT,
  AZURE_OPENAI_ENDPOINT,
  AZURE_OPENAI_KEY,
  AZURE_OPENAI_MODEL,
  EMAIL_CONFIRMATION_CODE_TTL_MINUTES,
  EMAIL_FROM,
  FRONT_URL,
  GOOGLE_GENERATIVE_AI_API_KEY,
  GOOGLE_GENERATIVE_AI_MODEL,
  JWT_SECRET,
  PORT,
  PRIVATE_KEY_BASE64,
  PUBLIC_KEY_BASE64,
  RESEND_API_KEY,
  SELF_BASE_URL,
};
