import "dotenv/config";

const {
  PORT,
  AZURE_OPENAI_DEPLOYMENT,
  AZURE_OPENAI_KEY,
  AZURE_OPENAI_ENDPOINT,
  AZURE_OPENAI_MODEL,
  GOOGLE_GENERATIVE_AI_API_KEY,
  GOOGLE_GENERATIVE_AI_MODEL,
  AI_SOURCE,
  PRIVATE_KEY_BASE64,
  PUBLIC_KEY_BASE64,
  SELF_BASE_URL,
} = process.env;

export {
  PORT,
  AZURE_OPENAI_DEPLOYMENT,
  AZURE_OPENAI_KEY,
  AZURE_OPENAI_ENDPOINT,
  AZURE_OPENAI_MODEL,
  GOOGLE_GENERATIVE_AI_API_KEY,
  GOOGLE_GENERATIVE_AI_MODEL,
  AI_SOURCE,
  PRIVATE_KEY_BASE64,
  PUBLIC_KEY_BASE64,
  SELF_BASE_URL,
};
